### ISSUE TITLE
TypeError: program.rpc.sendTweet is not a function

### ISSUE THREAD

**Issue by sreckovic** [lorisleiva/solana-twitter#3]
Looks likes function sendTweet is missing on program.rpc, I had to use:

```
await program.rpc.initialize("veganism", "Hummus, am I right?", {
 accounts: {
  tweet: tweet.publicKey,
  author: program.provider.wallet.publicKey,
  systemProgram: anchor.web3.SystemProgram.programId,
 },
 signers: [tweet],
});
```

if someone can confirm, thanks!

**Comment by sreckovic** [comment]
My bad, I didn't renamed `pub fn send_tweet` but just `ctx: Context<SendTweet>`, ...

**Comment by cdhiraj40** [comment]
> My bad, I didn't renamed `pub fn send_tweet` but just `ctx: Context<SendTweet>`, ...

hey @sreckovic, could you elaborate on this more? I am facing the same issue.
maybe @lorisleiva can help too? Thanks

**Comment by sreckovic** [comment]
@cdhiraj40 you need to call function like this

```
await program.rpc.sendTweet("veganism", "Hummus, am I right?", {
  accounts: {
    tweet: tweet.publicKey,
    author: program.provider.wallet.publicKey,
    systemProgram: anchor.web3.SystemProgram.programId,
  },
  signers: [tweet],
});
```

**Comment by cdhiraj40** [comment]
> @cdhiraj40 you need to call function like this
> 
> ```
> await program.rpc.sendTweet("veganism", "Hummus, am I right?", {
>   accounts: {
>     tweet: tweet.publicKey,
>     author: program.provider.wallet.publicKey,
>     systemProgram: anchor.web3.SystemProgram.programId,
>   },
>   signers: [tweet],
> });
> ```

I am actually calling this way only but I am still getting the error.

Also in my target/types the file  ``solana_twitter.ts`` does not contain this function it just contains the ``initialize`` function. maybe that's a problem?

**Comment by sreckovic** [comment]
Check lib.rs what is the name of function, not sure if I can help you beyond that.

**Comment by cdhiraj40** [comment]
@sreckovic @lorisleiva I just uploaded my files to my repo. I was taking the project for reference to what I wanted to make, could you please check once and tell me what was wrong? https://github.com/cdhiraj40/LeetDroid-Solana

**Comment by cdhiraj40** [comment]
it worked now!! thanks for your help @sreckovic 
And also thanks to @lorisleiva the documentation is just awesome!!
